theme: jekyll-theme-leap-day
title: <img src="https://cdn.discordapp.com/attachments/806343355264401478/820076457690398751/GBG-team-logo-125.png" alt="Gas Brake Go">
description: Team Info
markdown: GFM
