theme: jekyll-theme-leap-day
title: <img src="https://media.discordapp.net/attachments/806343355264401478/820076457690398751/GBG-team-logo-125.png?width=80&height=80" alt="Gas Brake Go">
description: Team Info
markdown: GFM
